import { test, expect } from "@playwright/test"
const token = "browser-api-token-2026-at-least-32-characters"
test("rich task fields, dependencies, authenticated comments and dispatch gates survive reload", async ({ page, request }) => {
  const auth = { Authorization: `Bearer ${token}` }
  let state = await (await request.get("/api/board", { headers: auth })).json()
  const create = async (id: string, title: string) => {
    const response = await request.post("/api/board", { headers: auth, data: { revision: state.revision, action: { type: "create", id, draft: { title, description: "", column: "todo" } } } })
    expect(response.ok()).toBe(true)
    state = await response.json()
  }
  await create("rich-parent", "Rich parent")
  await create("rich-child", "Rich child")
  await page.goto("/")
  await page.getByLabel("Shared password").fill("browser-test-password-2026")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await page.getByRole("button", { name: "Edit Rich child", exact: true }).click()
  let dialog = page.getByRole("dialog")
  await dialog.getByText("Task settings and dependencies", { exact: true }).click()
  await dialog.getByLabel("Assignee", { exact: true }).selectOption("claude")
  await dialog.getByLabel("Type", { exact: true }).selectOption("task")
  await dialog.getByLabel("Effort", { exact: true }).selectOption("high")
  await dialog.getByLabel("Model", { exact: true }).selectOption("default")
  await dialog.getByLabel("Harness", { exact: true }).selectOption("codex")
  await dialog.getByLabel("PR URL", { exact: true }).fill("https://github.com/example/repo/pull/1")
  await dialog.getByLabel("Parent card", { exact: true }).selectOption("rich-parent")
  await dialog.getByRole("checkbox", { name: "Rich parent", exact: true }).check()
  await dialog.getByRole("checkbox", { name: "Human review required before work", exact: true }).check()
  await dialog.getByRole("checkbox", { name: "Allow automatic merge after review", exact: true }).check()
  await expect(dialog.getByRole("button", { name: "Dispatch saved task" })).toBeDisabled()
  await dialog.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await page.getByRole("button", { name: "Edit Rich child", exact: true }).click()
  dialog = page.getByRole("dialog")
  await dialog.getByText("Task settings and dependencies", { exact: true }).click()
  await expect(dialog.getByLabel("Assignee", { exact: true })).toHaveValue("claude")
  await expect(dialog.getByRole("checkbox", { name: "Rich parent", exact: true })).toBeChecked()
  await expect(dialog.getByLabel("PR URL", { exact: true })).toHaveValue("https://github.com/example/repo/pull/1")
  await dialog.getByLabel("Add a comment", { exact: true }).fill("Keep this authenticated note")
  await dialog.getByRole("button", { name: "Add comment", exact: true }).click()
  await expect(dialog.getByText("Keep this authenticated note", { exact: true })).toBeVisible()
  await dialog.getByRole("button", { name: "Dispatch saved task" }).click()
  await expect(dialog.getByRole("status")).toContainText("Human review")
  const saved = await (await request.get("/api/cards/rich-child", { headers: auth })).json()
  expect(saved.card).toMatchObject({ type: "task", parentId: "rich-parent", dependencies: ["rich-parent"], effort: "high", model: "default", harness: "codex", automerge: true, needsHumanReview: true })
  expect(saved.card.comments.at(-1)).toMatchObject({ author: "you", body: "Keep this authenticated note" })
})
